Controllers/SellerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using SL_StockTrade.Models;
using SL_StockTrade.ViewModel;

namespace SL_StockTrade.Controllers
{
    [Authorize(Roles = "Admin,Seller")]
    public class SellerController : Controller
    {
        //Constructor Injection
        private readonly ISellerRepository _sallesRepository;
        private readonly IHostingEnvironment hostingEnvironment;

        public SellerController(ISellerRepository sallesRepository, IHostingEnvironment hostingEnvironment)
        {
            _sallesRepository = sallesRepository;
            this.hostingEnvironment = hostingEnvironment;
        }
                
        public ViewResult Index()
        {
            var model = _sallesRepository.GetAllSellers();
            return View(model);
        }
              
        public ViewResult Details(int id)
        {            

            SellerDetailsViewModel sellerDetailsViewModel = new SellerDetailsViewModel()
            {
                Seller = _sallesRepository.GetSeller(id),
                PageTitle = "Seller Details"
            };

            return View(sellerDetailsViewModel);
        }

        //Admin Side Controls
        public ViewResult AdminIndex()
        {
            var model = _sallesRepository.GetAllSellers();
            return View(model);
        }

        public ViewResult AdminDetails(int id)
        {
            Seller seller = _sallesRepository.GetSeller(id);
            if(seller == null)
            {
                Response.StatusCode = 404;
                return View("ErrorNotFound", id);
            }

            SellerDetailsViewModel sellerDetailsViewModel = new SellerDetailsViewModel()
            {
                Seller = seller,
                PageTitle = "Seller Details"
            };

            return View(sellerDetailsViewModel);
        }

        [HttpGet]
        public ViewResult AdminCreateSeller()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AdminCreateSeller(AdminCreateSellerViewModel model)
        {
            if(ModelState.IsValid)
            {
                string uniqueFileName = ProcessProfilPicture(model);
                string uniqueBannerName = ProcessBannerPicture(model);


                Seller newSeller = new Seller
                {
                    BusinessName = model.BusinessName,
                    InChargePerson = model.InChargePerson,
                    Country = model.Country,
                    Location = model.Location,
                    Address = model.Address,
                    Telephone = model.Telephone,
                    Mobile = model.Mobile,
                    Email = model.Email,
                    Web = model.Web,
                    PlatformCharge = model.PlatformCharge,
                    RegistredDate = model.RegistredDate,
                    BannerImg = uniqueBannerName,
                    ProfileImg = uniqueFileName,
                    SalesGoodType = model.SalesGoodType,
                    Description = model.Description
                };

                _sallesRepository.AdminCreateSeller(newSeller);
                return RedirectToAction("AdminDetails", new { id = newSeller.Id });
            }

            return View();
        }

        [HttpGet]
        public ViewResult AdminEditSeller(int id)
        {
            Seller seller = _sallesRepository.GetSeller(id);

            if (seller == null)
            {
                Response.StatusCode = 404;
                return View("ErrorNotFound", id);
            }

            AdminEditSellerViewModel adminEditSellerViewModel = new AdminEditSellerViewModel
            {
                Id = seller.Id,
                BusinessName = seller.BusinessName,
                InChargePerson = seller.InChargePerson,
                Country = seller.Country,
                Location = seller.Location,
                Address = seller.Address,
                Telephone = seller.Telephone,
                Mobile = seller.Mobile,
                Email = seller.Email,
                Web = seller.Web,
                PlatformCharge = seller.PlatformCharge,
                RegistredDate = seller.RegistredDate,
                ExisitingProfilePhotoPath = seller.ProfileImg,
                ExisitingBannerPhotoPath = seller.BannerImg,
                SalesGoodType = seller.SalesGoodType,
                Description = seller.Description
            };

            return View(adminEditSellerViewModel);
        }

        [HttpPost]
        public IActionResult AdminEditSeller(AdminEditSellerViewModel model)
        {
            if (ModelState.IsValid)
            {
                Seller seller = _sallesRepository.GetSeller(model.Id);
                seller.BusinessName = model.BusinessName;
                seller.InChargePerson = model.InChargePerson;
                seller.Country = model.Country;
                seller.Location = model.Location;
                seller.Address = model.Address;
                seller.Telephone = model.Telephone;
                seller.Mobile = model.Mobile;
                seller.Email = model.Email;
                seller.Web = model.Web;
                seller.PlatformCharge = model.PlatformCharge;
                seller.RegistredDate = model.RegistredDate;
                seller.BannerImg = model.ExisitingProfilePhotoPath;
                seller.ProfileImg = model.ExisitingProfilePhotoPath;
                seller.SalesGoodType = model.SalesGoodType;
                seller.Description = model.Description;
                if (model.ProfilePic != null)
                {
                    if(model.ExisitingProfilePhotoPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath, "img/Profile", model.ExisitingProfilePhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    seller.ProfileImg=ProcessProfilPicture(model);
                }
                
                if(model.BannerPic != null)
                {
                    if (model.ExisitingBannerPhotoPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath, "img/Cover", model.ExisitingBannerPhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    seller.BannerImg = ProcessBannerPicture(model);
                }

                _sallesRepository.AdmimUpdateSeller(seller);
                return RedirectToAction("Index");
            }

            return View();
        }

        private string ProcessBannerPicture(AdminCreateSellerViewModel model)
        {
            string uniqueBannerName = null;


            if (model.BannerPic != null)
            {
                string uploadFolder = Path.Combine(hostingEnvironment.WebRootPath, "img/Cover");
                uniqueBannerName = Guid.NewGuid().ToString() + "_" + model.BannerPic.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueBannerName);
                using(var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.BannerPic.CopyTo(fileStream);
                }
               
            }

            return uniqueBannerName;
        }

        private string ProcessProfilPicture(AdminCreateSellerViewModel model)
        {
            string uniqueFileName = null;

            if (model.ProfilePic != null)
            {
                string uploadFolder = Path.Combine(hostingEnvironment.WebRootPath, "img/Profile");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ProfilePic.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ProfilePic.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

Views/Shared/NotFound.cshtml
@{ 
    ViewBag.Title = "Not Found";
}

<h3  class="alert alert-info">@ViewBag.ErrorMessage</h3>

<a asp-action="index" asp-controller="home">
    Click here to navigate to the home page
</a>

Views/Shared/_Layout.cshtml
@inject SignInManager<SellerDeviceData> signInManager;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SL_StockTrade</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DR-Lanka</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    System Admin
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-action="AdminIndex" asp-controller="Seller">Manage Shops</a>
                                    <a class="dropdown-item" asp-action="CreateRole" asp-controller="Admin">Create New Role</a>
                                    <a class="dropdown-item" asp-action="ListRoles" asp-controller="Admin">View All Roles</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }
                        else if (signInManager.IsSignedIn(User) && User.IsInRole("Buyer"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Buyer
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                </div>
                            </li>
                        }
                        else if (signInManager.IsSignedIn(User) && User.IsInRole("Seller"))
                        {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Seller
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                    <a class="dropdown-item" asp-action="AdminCreateSeller" asp-controller="Seller">Create New Shop</a>
                                    <a class="dropdown-item" asp-controller="Seller" asp-action="Index">My Shops</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                </div>
                            </li>
                        }

                    </ul>
                    <ul class="navbar-nav ml-auto  my-2 my-lg-0 float-right">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="account">
                                    <button type="submit" class="nav-link btn btn-link py-0 btn-warning" style="width:auto">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-action="SellerSignIn" asp-controller="Account" class="nav-link">Sign In</a>
                            </li>

                            <li class="nav-item">
                                <a asp-action="SellerRegister" asp-controller="Account" class="nav-link">Sign Up</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SL_StockTrade - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: true)
    }

</body>
</html>